{
  imports = [
    ./audio.nix
    ./avahi.nix
    ./batmon.nix
    ./bluetooth.nix
    ./fwupd.nix
    ./graphics.nix
    ./grub.nix
    ./libinput.nix
    ./localsend.nix
    ./logind.nix
    ./nfs-mounts.nix
    ./swapescape.nix
    ./tlp.nix
    ./unfree-whitelist.nix
    ./upower.nix
    ./wireguard.nix
  ];
}
