keys:
  - hosts:
    - &liberty age14q30ynrxljm276k52yzud3ppk6awh8h30k5etrlccn9mux95e43ss39rfe
    - &donnager age1kcydglemswdtsk5j92gm9dtwdql33e68z3krzy0cvth6a0rpue6se2qvuf
    - &t480 age1n67a6mxvmtk89jgs3lutm4nyjyautwsf7v2ssu0s2pzxle2dgvlsyhxnez
    - &rpi5-1 age1lkvaqekxfqzg9m354nwr0dprgfwm6l858y4ux0hd3pru3wrj33hq5gq2hw
    - &rpi5-2 age16ysmvc64mv9zwxjy976cdgq54j8ujrj47gds4rksmjy25r573c4sey5jh3
    - &linode age1zya84hkcxynmr7rc9k8umyngnclwr73xed8xp2l7ljjmvql4yuyqgue9ar
    - &ganymede age15g4wvczmefaejpr4xjtvtnty42g5qggjrpdtemh7mnspuvxz53usenlym0
  - users:
    - &liyua-master age1x0tt0aw933scsms872xynu2henqa5rll4m6pajxj6f6m2242mp6sl3jer9
    - &liyua-ganymede age19jfpmmmqpzd3tvqyqh94tdszhqegram6q2hrefd46p89hjxvhp0qydzs7n
creation_rules:
  - &system
    path_regex: secrets/system.yaml$
    key_groups:
      - age:
        - *liyua-master
        - *liberty
        - *donnmager
        - *t480
        - *rpi5-1
        - *rpi5-2
        - *linode
        - *ganymede
  - &user
    path_regex: secrets/liyua.yaml$
    key_groups:
      - age:
        - *liyua-master
        - *liyua-ganymede
stores:
  yaml:
    indent: 2
