keys:
  - &liyua age1x0tt0aw933scsms872xynu2henqa5rll4m6pajxj6f6m2242mp6sl3jer9
  - &liberty age14q30ynrxljm276k52yzud3ppk6awh8h30k5etrlccn9mux95e43ss39rfe
  - &t480 age1efvve8f2dnyyhv8y0jfmkcdadpzkx2ldxh3ezua0hnc97p454feq8t66zp
  - &rpi5-2 age16ysmvc64mv9zwxjy976cdgq54j8ujrj47gds4rksmjy25r573c4sey5jh3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *liyua
        - *liberty
        - *t480
        - *rpi5-2
