# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/d209daa6-405c-4eb5-b152-c7c5e8095820";
#      fsType = "btrfs";
#      options = [ "subvol=root" ];
#    };

#  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/fba06bf2-9af2-424f-853b-e0a5a1c63b74";

#  fileSystems."/.swapvol" =
#    { device = "/dev/disk/by-uuid/d209daa6-405c-4eb5-b152-c7c5e8095820";
#      fsType = "btrfs";
#      options = [ "subvol=swap" ];
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/61DB-0E23";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/9eb92d89-b147-4c52-a179-de3d2918160a";
#      fsType = "btrfs";
#      options = [ "subvol=home" ];
#    };

#  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/1d472881-72d7-4187-9466-81f8bc606287";

#  fileSystems."/nix" =
#    { device = "/dev/disk/by-uuid/d209daa6-405c-4eb5-b152-c7c5e8095820";
#      fsType = "btrfs";
#      options = [ "subvol=nix" ];
#    };

#  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
