backend = "full"
palette = "ansidark16"
color_space = "lch"
check_contrast = true

[templates]
nvim.template = "nvim.vim"
nvim.target = "~/.cache/wal/colors-wal.vim"

json.template = "colors.json"
json.target = "~/.cache/wal/colors.json"

kitty.template = "kitty.conf"
kitty.target = "~/.config/kitty/colors.conf"

hypr.template = "hyprland.hl"
hypr.target = "~/.config/hypr/colors.hl"

btop.template = "btop.theme"
btop.target = "~/.config/btop/themes/wallust.theme"

wofi.template = "wofi.css"
wofi.target = "~/.config/wofi/style.css"

discord.template = "discord.theme.css"
discord.target="~/.config/vesktop/themes/wallust.theme.css"

zathura.template = "zathura"
zathura.target = "~/.config/zathura/colors"

scss.template = "colors.scss"
scss.target = "~/.config/ags/style/colors.scss"
