backend = "resized"
palette = "ansidark"
color_space = "lch"
check_contrast = true

[templates]
nvim.template = "nvim.vim"
nvim.target = "~/.cache/wallust/colors_neopywal.vim"

kitty.template = "kitty.conf"
kitty.target = "~/.config/kitty/colors.conf"

hypr.template = "hyprland.hl"
hypr.target = "~/.config/hypr/colors.hl"

btop.template = "btop.theme"
btop.target = "~/.config/btop/themes/wallust.theme"
