exec-once = hyprctl dispatch movecursor 50% 50%

exec-once = ~/.local/bin/apps/mullvad.sh
exec-once = ~/.local/bin/apps/discord.sh --start-minimized &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = ~/.local/bin/theme/theme.sh

