exec-once = ~/.local/bin/apps/mullvad.sh
exec-once = wl-paste --watch cliphist store &

exec-once = ~/.local/bin/theme/theme.sh
exec-once = systemctl --user start plasma-polkit-agent
exec-once = .local/bin/apps/terminal.sh -a term-btop btop &
exec = hyprpm reload -n

