monitor = eDP-1,1920x1080@60,0x0,1

input {
  kb_layout = de
  follow_mouse = 1
  accel_profile = flat
}

windowrulev2 = workspace 3 silent, class:vesktop
windowrulev2 = workspace 4 silent, class:steam
windowrulev2 = workspace 4 silent, title:Steam

exec-once = hyprctl dispatch movecursor 960 540

bind = , XF86Launch2, exec, steam steam://rungameid/524220
bind = , XF86Calculator, pass
