exec = hyprpm reload

# Variables
source = vars.conf

# keybinds
source = keybinds.conf

# Autostart
source = autostart.conf

# Theming
source = theming.conf

# Miscellanious Options
source = options.conf

# Layout options
source = layout.conf

# Plugin-specific configs
source = plugins.conf

# Window-, workspace- and layerrules
source = windowrules.conf

# Device-specific configuration
source = local.conf

