monitor = eDP-1,2560x1600@165,0x0,1.6

input {
  kb_layout = de
  follow_mouse = 1
  accel_profile = flat
}

windowrulev2 = workspace 3 silent, class:vesktop
windowrulev2 = workspace 4 silent, class:steam
windowrulev2 = workspace 4 silent, title:Steam
windowrulev2 = workspace 5 silent, class:^(steam_app_.*)$
windowrulev2 = workspace 6 silent, class:^(term-btop)$

exec-once = hyprctl dispatch movecursor 800 500

xwayland {
  enabled = true
  force_zero_scaling = true
}

env = GDK_SCALE,1.5

plugins:touch_gestures {
  sensitivity = 1.0
  workspace_swipe_fingers = 3
  long_press_delay = 400
  edge_margin = 50
}

gestures {
  workspace_swipe = true
  workspace_swipe_cancel_ratio = 0.15
}

# hyprgrass-bind = , edge:l:r, workspace, -1
# hyprgrass-bind = , edge:r:l, workspace, +1
# hyprgrass-bindm = , longpress:2, movewindow
# hyprgrass-bindm = , longpress:3, 3, resizewindow
# hyprgrass-bind = , tap:3, exec, ~/.local/bin/apps/terminal.sh
# hyprgrass-bind = , tap:4, killactive

bind = SUPER SHIFT, XF86TouchpadOff, exec, steam steam://rungameid/524220

decoration {
  drop_shadow = false
}

misc {
  vfr = true
}
