monitor = eDP-1,2560x1600@165,0x0,1.6

input {
  kb_layout = de
  follow_mouse = 1
  accel_profile = flat
  left_handed = false
}

windowrulev2 = workspace 3 silent, class:vesktop
windowrulev2 = workspace 4 silent, class:steam
windowrulev2 = workspace 4 silent, title:Steam
windowrulev2 = workspace 5 silent, class:^(steam_app_.*)$
windowrulev2 = workspace 6 silent, class:^(term-btop)$

exec-once = hyprctl dispatch movecursor 800 500

xwayland {
  enabled = true
  force_zero_scaling = true
}

env = GDK_SCALE,1.5
env = GSK_RENDERER,gl

plugins:touch_gestures {
  sensitivity = 4.0
  workspace_swipe_fingers = 3
  long_press_delay = 400
}

gestures {
  workspace_swipe = true
  workspace_swipe_cancel_ratio = 0.15
}

bind = SUPER SHIFT, XF86TouchpadOff, exec, steam steam://rungameid/524220

decoration {
  drop_shadow = false
}

misc {
  vfr = true
}
