monitor=DP-3,3440x1440@144,0x0,1
monitor=HDMI-A-1,1920x1080@60,-1920x0,1

input {
  kb_layout = us
  follow_mouse = 1
  accel_profile = flat
}

general {
  allow_tearing = true
}

exec-once = hyprctl dispatch movecursor 1720 720
exec-once = ~/.local/bin/apps/discord.sh &
exec-once = ~/.local/bin/apps/steam.sh &
exec-once = systemctl --user start plasma-polkit-agent

windowrulev2 = workspace 12 silent, class:^(term-btop)$
windowrulev2 = workspace 13 silent, class:^(vesktop)$
windowrulev2 = workspace 14 silent, class:^(steam)$

windowrulev2 = workspace 1 silent,class:^(steam_app_.*)$
windowrulev2 = immediate,class:^(steam_app_.*)$
windowrulev2 = fullscreenstate 3 3,class:^(steam_app_.*)$
windowrulev2 = allowsinput on,class:^(steam_app_.*)$

windowrulev2 = workspace 1 silent,class:^(Minecraft.*)$
windowrulev2 = fullscreen,class:^(Minecraft.*)$

