monitor=DP-3,3440x1440@144,0x0,1
monitor=HDMI-A-1,1920x1080@60,3440x0,1

input {
    kb_layout = us
    follow_mouse = 1
    accel_profile = flat
}

exec-once = hyprctl dispatch movecursor 1720 720
exec-once = ~/.local/bin/apps/discord.sh --start-minimized &

windowrulev2 = workspace 13 silent, class:^(vesktop)$
