$terminal = ~/.local/bin/apps/terminal.sh
$fileManager = ~/.local/bin/apps/fileexplorer.sh
$browser = ~/.local/bin/apps/browser.sh
$menu = ~/.local/bin/apps/launcher.sh

$xdg_config = /home/$USER/.config
$xdg_cache = /home/$USER/.cache
$xdg_data = /home/$USER/.local/share
$xdg_state = /home/$USER/.local/state

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Ice

env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1
env = QT_QPA_PLATFORMTHEME,qt6ct
env = MOZ_ENABLE_WAYLAND,1
env = GDK_BACKEND,wayland

env = XDG_DATA_HOME,$xdg_data
env = XDG_CACHE_HOME,$xdg_cache
env = XDG_CONFIG_HOME,$xdg_config
env = XDG_STATE_HOME,$xdg_state
env = TEXMFHOME,$xdg_data/texmf
env = TEXMFVAR,$xdg_cache/texlive/texmf-var
env = TEXMFCONFIG,$xdg_config/texlive/texmf-config
env = GOPATH,$xdg_data/go
env = CARGO_HOME,$xdg_data/cargo
env = RUSTUP_HOME,$xdg_data/rustup
env = ZDOTDIR,$xdg_config/zsh
