# Windows can't automatically maximize
windowrulev2 = suppressevent maximize, class:.*

# Steam apps allow tearing (might have to be ebabled via the global toggle first)
windowrulev2 = immediate, class:^(steam_app_.*)$

# Wofi always stays focused until an app is launched or it is closed
windowrulev2 = stayfocused, floating:1, class:^(wofi)$

# Transparent apps
$opacity = 0.8
windowrulev2 = opacity $opacity $opacity override, class:^(term.*)$
windowrulev2 = noblur, class:^(term.*)$

windowrulev2 = opacity $opacity $opacity override, class:^(vesktop)$
windowrulev2 = opacity $opacity $opacity override, class:^(steam)$
windowrulev2 = opacity $opacity $opacity override, class:^(thunar)$

# windowrulev2 = float,class:^(onboard.*)$
# windowrulev2 = size 100% 50%,class:^(onboard.*)$
# windowrulev2 = move 0 50%,class:^(onboard.*)$

windowrulev2 = float,title:^(Welcome to IntelliJ)$
windowrulev2 = stayfocused,class:^(jetbrains-idea-.*)$,title:^(win.*)$
windowrulev2 = allowsinput on,class:^(jetbrains-idea-.*)$,title:^(win.*)$
windowrulev2 = focusonactivate on,class:^(jetbrains-idea-.*)$,title:^(win.*)$

windowrulev2 = workspace 1 silent,class:^(Minecraft.*)$
windowrulev2 = fullscreen,class:^(Minecraft.*)$

# Blur for waybar and mako
# layerrule = blur, waybar
layerrule = blur, notifications

