# Windows can't automatically maximize
windowrulev2 = suppressevent maximize, class:.*

# Steam apps allow tearing (might have to be ebabled via the global toggle first)
windowrulev2 = immediate, class:^(steam_app_.*)$
windowrulev2 = opacity 1 override, class:^(steam_app_.*)$

# Wofi always stays focused until an app is launched or it is closed
windowrulev2 = stayfocused, floating:1, class:^(wofi)$

# LibreWolf won't be displayed as transparent
windowrulev2 = opacity 1 override, class:^(LibreWolf)$
# librewolf-bin and librewolf have different window classes :/
windowrulev2 = opacity 1 override, class:^(librewolf)$
# Remove transparency from gimp
windowrulev2 = opacity 1 override, class:^(Gimp-.*)$
# Remove transparency from Minecraft
windowrulev2 = opacity 1 override, class:^(Minecraft.*)$

# Blur for waybar and mako
# layerrule = blur, waybar
layerrule = blur, notifications

