windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = immediate, class:^(steam_app_*)$
windowrulev2 = stayfocused, floating:1
windowrulev2 = float, title:^((.*)Extension(.*))$
windowrulev2 = stayfocused, class:^(wofi)$

layerrule = blur, waybar
layerrule = blur, notifications

