{
  imports = [
    ./lzn.nix
    ./nix.nix
    ./dressing.nix
    ./blink.nix
    ./telescope.nix
    ./treesitter.nix
    ./devicons.nix
    ./neotree.nix
    ./lualine.nix
    ./bufferline.nix
    ./autopairs.nix
    ./autosession.nix
    ./conform.nix
    ./lspconfig.nix
    ./whichkey.nix
    ./tsautotag.nix
    ./gitsigns.nix
  ];
}
